### ISSUE TITLE
How to specify Tags for Cost Allocations report

### ISSUE THREAD

**Issue by HumanSolutions** [chris-bowman/Azure-Cost-Reporting#13]
Thanks for sharing this tool. I have found it very useful. I have 7 tags. Is there a way to list and report on them in Cost allocations tab? thanks again.

**Comment by chris-bowman** [comment]
Hi @HumanSolutions, 
The sample report has a couple of example extractions for the Tags field, you will find Tags.CostCentre and Tags.Application in the Resources table, which are fairly common. You can copy the DAX and make a new column, substituting the LookupKey for the tag you are searching for. You can then add these into the Cost Allocations tab for your 7 tags.

I did previously parse the JSON in the Power Query during import, but found it ended up erroring or timing out more often than not due to the sheer volume of tags and free-form in the deployments, so instead extracted only what is necessary for the report.
